name: Deploy App to AWS Elastic Beanstalk Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

      - name: Zip the build folder
        run: zip -r build.zip dist .ebextensions package.json package-lock.json server.js

      - name: Get SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          application_name: TimeTrack
          environment_name: TimeTrack-env
          version_label: "app-${{ steps.get_sha.outputs.sha }}"
          region: eu-west-1
          deployment_package: build.zip
